receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:


exporters:
  datadog:
    idle_conn_timeout: 10s
    api:
      key: ${env:DD_API_KEY}
#    logs:
#      use_compression: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [datadog]
  telemetry:
    logs:
      level: "debug"